default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ensyu2_development

test:
  <<: *default
  database: ensyu2_test

production:
  <<: *default
  database: ensyu2_production
  username: ensyu2
  password: <%= ENV['ENSYU2_DATABASE_PASSWORD'] %>
